application/views.py
from flask import Flask, Blueprint, render_template, request, send_from_directory, redirect, session
# from flask.ext.sqlalchemy import SQLAlchemy
import logging
from logging import Formatter, FileHandler
from .utils.forms import *
import os
import werkzeug
import jinja2
import os
from .utils.forms import LoginForm
from .utils import gmail_api


bp = Blueprint("bp", __name__)



# Automatically tear down SQLAlchemy.
'''
@app.teardown_request
def shutdown_session(exception=None):
    db_session.remove()
'''

# Login required decorator.
'''
def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('login'))
    return wrap
'''

@bp.route('/')
def home():
    session["previous"] = "/"
    return render_template('pages/index.html')

@bp.route('/about')
def about():
    session["previous"] = "/about"
    return render_template('pages/project.html')

@bp.route('/info')
def info():
    session["previous"] = "/info"
    return render_template('pages/info.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    session["previous"] = "/login"
    while(request.method == "POST"):
        if login_form.is_submitted and login_form.agreed.data == True:
            gmail = gmail_api.Gmail()
            session['state'] = gmail.state
            print(session['state'])
            return redirect(gmail.authorization_url)
        else:
            return "You must agree to continue"
    return render_template('forms/login.html', form=login_form)


@bp.route('/attm_download')
def attm_download():
    return "<h2>Attachment preview isn't supported nor download so far</h2>"


''''
@bp.route('/register')
def register():
    form = RegisterForm(request.form)
    return render_template('forms/register.html', form=form)
@bp.route('/forgot')
def forgot():
    form = ForgotForm(request.form)
    return render_template('forms/forgot.html', form=form)
'''

@bp.route('/static/css/<path:filename>')
def static_files_css(filename):
    return send_from_directory('../static/css/', filename=filename)

@bp.route('/static/fonts/<path:filename>')
def static_files_fonts(filename):
    return send_from_directory('../static/fonts/', filename=filename)

@bp.route('/static/ico/<path:filename>')
def static_files_icos(filename):
    return send_from_directory('../static/ico', filename=filename)

@bp.route('/static/js/<path:filename>')
def static_files_js(filename):
    return send_from_directory('../static/js/', filename=filename)


# Error handlers.

templates/pages/draft.dashboard.html
{% extends 'layouts/main.dashboard.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="page-header">
    <h1>✉ Drafts <code>for {{ user_metadata['emailAddress'] }}</code></h1>
</div>
<div class="lead">
    {% if drafts|length==0 %}
    No messages to display here...
    {% endif %}

    <div id="accordion">
      {% for msg in drafts %}
        <div class="well well-sm card">
          <div class="card-header" id="heading{{ loop.index0 }}">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
               <small class="text-muted">{{ msg.date }}</small>
               <p class="h5"> to {{ msg.recipient }}</p>
               <br>
               <p class="h3">{{ msg.subject }}</p>
               {% if msg.attachments %}
               {% for attm in msg.attachments %}
               <p><a href="{{ url_for('bp.attm_download') }}">{{ attm.filename }}</a></p>
               {% endfor %}
              {% endif %}
            </button>
          </div>
          <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordion">
            <div class="card-body">
              {{ msg.html | safe }}
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
</div>

  <!-- Modal -->

  <div class="modal fade" id="composeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" class="form" action="{{ url_for('db_bp.message_submit') }}">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    {{ compose_form.recipient(class_ = 'form-control second-input', placeholder = compose_form.recipient.label.text, required = true) }}
                    {{ compose_form.subject(class_ = 'form-control first-input', placeholder = compose_form.subject.label.text, required = true) }}
                    {{ compose_form.body(class_ = 'form-control last-input bodyField', placeholder = compose_form.body.label.text, required = true) }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to logout?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="logoutModalButton" class="btn btn-primary">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    document.getElementById("logoutModalButton").onclick = function () {
        location.href = "/revoke";
    };
 </script>
{% endblock %}

templates/pages/inbox.dashboard.html
{% extends 'layouts/main.dashboard.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="page-header">
    <h1>📪 Inbox <code>for {{ user_metadata['emailAddress'] }}</code></h1>
</div>
<div class="lead">
    {% if inbox|length==0 %}
    No messages to display here...
    {% endif %}
    <div id="accordion">
    {% for msg in inbox %}
      <div class="well well-sm card">
        <div class="card-header" id="heading{{ loop.index0 }}">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
             <small class="text-muted">{{ msg.date }}</small>
             <p class="h5"> from {{ msg.sender }}</p>
             <br>
             <p class="h3">{{ msg.subject }}</p>
             {% if msg.attachments %}
              {% for attm in msg.attachments %}
              <p><a href="{{ url_for('bp.attm_download') }}">{{ attm.filename }}</a></p>
              {% endfor %}
             {% endif %}
          </button>
        </div>
        <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordion">
          <form method="POST" action="{{ url_for('db_bp.modify') }}?action=trash">
            {{ trash_form.csrf_token }}
            {{ trash_form.id(class_ = 'form-control last-input', readonly="readonly", placeholder = trash_form.id.label.text, required = true, value=msg.id) }}
            <input type="submit" value="Trash">
          </form>
          <div class="card-body">
            {{ msg.html | safe }}
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>

  <!-- Modal -->

  <div class="modal fade" id="composeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" class="form" action="{{ url_for('db_bp.message_submit') }}">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    {{ compose_form.recipient(class_ = 'form-control second-input', placeholder = compose_form.recipient.label.text, required = true) }}
                    {{ compose_form.subject(class_ = 'form-control first-input', placeholder = compose_form.subject.label.text, required = true) }}
                    {{ compose_form.body(class_ = 'form-control last-input bodyField', placeholder = compose_form.body.label.text, required = true) }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to logout?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="logoutModalButton" class="btn btn-primary">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    document.getElementById("logoutModalButton").onclick = function () {
        location.href = "/revoke";
    };
 </script>
{% endblock %}

templates/pages/index.html
{% extends 'layouts/main.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1 class="page-header">Hello There</h1>
<div class="lead">
    <img src="https://www.memesmonkey.com/images/memesmonkey/a6/a65f9aeff5a7a209c2b04bd216ab0605.jpeg" alt="image">
    <p>image from memesmonkey.com</p>
</div>
{% endblock %}

templates/pages/placeholder.about.html
{% extends 'layouts/main.html' %}
{% block title %}About{% endblock %}
{% block content %}

<div class="page-header">
  <h1>About Page</h1>
</div>
<p class="lead">This is just a placeholder page which should be replaced with real content.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tellus ligula, imperdiet id lobortis sit amet, scelerisque non sapien. Duis quis dui quis mauris dapibus fringilla. Pellentesque nec tellus ac diam volutpat malesuada.</p>
<p>In quam arcu, interdum vel arcu viverra, vulputate convallis massa. Sed hendrerit velit a arcu euismod, sit amet consequat lacus imperdiet. Nullam quis dui sapien. Vestibulum placerat, justo non fringilla laoreet, dui ipsum posuere nisi, nec vestibulum eros leo ut sapien.</p>
<p>Vivamus eu felis sed magna scelerisque semper in et libero. Curabitur sed convallis odio, quis venenatis sapien. In convallis a velit ac commodo. Donec sapien ligula, vestibulum ut nisi accumsan, facilisis pretium est. Fusce varius semper orci, et egestas nulla cursus a. Phasellus aliquam, mi ac adipiscing lobortis, ipsum augue aliquam ligula, quis fermentum mi augue vel ligula.</p>
<p>Integer elementum malesuada dolor in aliquet.</p>

{% endblock %}

templates/pages/placeholder.home.html
{% extends 'layouts/main.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="page-header">
  <h1>Sticky footer with fixed navbar</h1>
</div>
<p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added within <code>#wrap</code> with <code>padding-top: 60px;</code> on the <code>.container</code>.</p>

{% endblock %}

templates/pages/sent.dashboard.html
{% extends 'layouts/main.dashboard.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="page-header">
    <h1>📤 Sent Items <code>for {{ user_metadata['emailAddress'] }}</code></h1>
</div>
<div class="lead">
  <div id="accordion">
    {% if sents|length==0 %}
    No messages to display here...
    {% endif %}

    {% for msg in sents %}
      <div class="well well-sm card">
        <div class="card-header" id="heading{{ loop.index0 }}">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
             <small class="text-muted">{{ msg.date }}</small>
             <p class="h5"> to {{ msg.recipient }}</p>
             <br>
             <p class="h3">{{ msg.subject }}</p>
             {% if msg.attachments %}
              {% for attm in msg.attachments %}
              <p><a href="{{ url_for('bp.attm_download') }}">{{ attm.filename }}</a></p>
              {% endfor %}
             {% endif %}
          </button>
        </div>
        <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordion">
          <div class="card-body">
            {{ msg.html | safe }}
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>

  <!-- Modal -->

  <div class="modal fade" id="composeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" class="form" action="{{ url_for('db_bp.message_submit') }}">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    {{ compose_form.recipient(class_ = 'form-control second-input', placeholder = compose_form.recipient.label.text, required = true) }}
                    {{ compose_form.subject(class_ = 'form-control first-input', placeholder = compose_form.subject.label.text, required = true) }}
                    {{ compose_form.body(class_ = 'form-control last-input bodyField', placeholder = compose_form.body.label.text, required = true) }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to logout?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="logoutModalButton" class="btn btn-primary">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    document.getElementById("logoutModalButton").onclick = function () {
        location.href = "/revoke";
    };
 </script>
{% endblock %}

templates/pages/starred.dashboard.html
{% extends 'layouts/main.dashboard.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="page-header">
    <h1>⭐ Starred Messages <code>for {{ user_metadata['emailAddress'] }}</code></h1>
</div>
<div class="lead">
  <div id="accordion">
    {% if starred|length==0 %}
    No messages to display here...
    {% endif %}

    {% for msg in starred %}
      <div class="well well-sm card">
        <div class="card-header" id="heading{{ loop.index0 }}">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
             <small class="text-muted">{{ msg.date }}</small>
             <p class="h5"> from {{ msg.sender }}</p>
             <br>
             <p class="h3">{{ msg.subject }}</p>
             {% if msg.attachments %}
              {% for attm in msg.attachments %}
              <p><a href="{{ url_for('bp.attm_download') }}">{{ attm.filename }}</a></p>
              {% endfor %}
             {% endif %}
          </button>
        </div>
        <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordion">
          <div class="card-body">
            {{ msg.html | safe }}
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>

  <!-- Modal -->

  <div class="modal fade" id="composeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" class="form" action="{{ url_for('db_bp.message_submit') }}">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    {{ compose_form.recipient(class_ = 'form-control second-input', placeholder = compose_form.recipient.label.text, required = true) }}
                    {{ compose_form.subject(class_ = 'form-control first-input', placeholder = compose_form.subject.label.text, required = true) }}
                    {{ compose_form.body(class_ = 'form-control last-input bodyField', placeholder = compose_form.body.label.text, required = true) }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to logout?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="logoutModalButton" class="btn btn-primary">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    document.getElementById("logoutModalButton").onclick = function () {
        location.href = "/revoke";
    };
 </script>
{% endblock %}

templates/pages/trash.dashboard.html
{% extends 'layouts/main.dashboard.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="page-header">
    <h1>🗑️ Trash <code>for {{ user_metadata['emailAddress'] }}</code></h1>
</div>
<div class="lead">
  <div id="accordion">
    {% if trash|length==0 %}
    No messages to display here...
    {% endif %}

    {% for msg in trash %}
      <div class="well well-sm card">
        <div class="card-header" id="heading{{ loop.index0 }}">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
             <small class="text-muted">{{ msg.date }}</small>
             <p class="h5"> from {{ msg.sender }}</p>
             <br>
             <p class="h3">{{ msg.subject }}</p>
             {% if msg.attachments %}
              {% for attm in msg.attachments %}
              <p><a href="{{ url_for('bp.attm_download') }}">{{ attm.filename }}</a></p>
              {% endfor %}
             {% endif %}
          </button>
        </div>
        <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordion">
          <div class="card-body">
            {{ msg.html | safe }}
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
</div>

  <!-- Modal -->

  <div class="modal fade" id="composeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" class="form" action="{{ url_for('db_bp.message_submit') }}">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    {{ compose_form.recipient(class_ = 'form-control second-input', placeholder = compose_form.recipient.label.text, required = true) }}
                    {{ compose_form.subject(class_ = 'form-control first-input', placeholder = compose_form.subject.label.text, required = true) }}
                    {{ compose_form.body(class_ = 'form-control last-input bodyField', placeholder = compose_form.body.label.text, required = true) }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to logout?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button id="logoutModalButton" class="btn btn-primary">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    document.getElementById("logoutModalButton").onclick = function () {
        location.href = "/revoke";
    };
 </script>
{% endblock %}